version: 2

jobs:
  build:
    machine: true
    steps:
      - run: mkdir -p ~/pkg ~/cache ~/keys
      - run: echo "$RELEASE_VERSION $OMNIBUS_BRANCH" > ~/cache_key.txt
      - restore_cache:
          keys:
            - omnibus-rpm-cache-{{ checksum "~/cache_key.txt" }}
      - run: docker run -e RELEASE_VERSION=$RELEASE_VERSION -e OMNIBUS_BRANCH=$OMNIBUS_BRANCH -v /home/circleci/pkg:/dd-agent-omnibus/pkg -v /home/circleci/cache:/var/cache/omnibus jfullaondo/docker-dd-agent-build-rpm-x64:latest
      - save_cache:
          key: omnibus-rpm-cache-{{ checksum "~/cache_key.txt" }}
          paths:
            - ~/cache
      - store_artifacts:
          path: ~/pkg

workflow_filters: &workflow_filters
  filters:
    branches:
      ignore:
        - /.*/

workflows:
  version: 2
  build_rpm:
    jobs:
      - build: *workflow_filters
